### ISSUE TITLE
 The kinematics plugin (arm_1) failed to load.

### ISSUE THREAD

**Issue by StanleyYake** [svenschneider/youbot-manipulation#7] opened 2015-05-08 05:38 UTC
Hello svenschneider:
I'm using ROS Hydro on Ubuntu 12.04LTS, after git clone youbot-manipulation in my catkin_ws/src and catkin_make, it is all no mistakes, but then I launch the `move_group.launch` and the `demo.launch`it reminds me the following error
![screenshot from 2015-05-08 12 54 01](https://cloud.githubusercontent.com/assets/7522853/7531058/73a741c8-f586-11e4-8c4c-a812268a4420.png)
![screenshot from 2015-05-08 12 53 12](https://cloud.githubusercontent.com/assets/7522853/7531061/7f0073f0-f586-11e4-93e0-7984f42aa25b.png)

and I also checked the catkin_ws/devel/lib , there is truly have the libyoubot_arm_kinematics_moveit.so
and libyoubot_arm_kinematics.so.

by the way, I have delete the source file and remove the specific file all about youbot-manipulation and bulid using the catkin_make the second time(that is delete,git clone,and catkin_make).Thanks in advance ！

**Comment by svenschneider** [comment] 2015-05-19 14:12
Dear StanleyYake,

sorry for the delayed answer. Unfortunately, I cannot reproduce this problem here. Therefore, it would be helpful, if you pasted the exact sequence of commands that you have executed and all resulting outputs from the terminal.

However, some wild guesses that you could try out:
1) Make sure that all ROS and especially MoveIt! requirements are installed:

```
apt-get install \
  ros-hydro-roscpp \
  ros-hydro-pluginlib \
  ros-hydro-urdf \
  ros-hydro-tf-conversions \
  ros-hydro-joint-state-publisher \
  ros-hydro-robot-state-publisher \
  ros-hydro-xacro
apt-get install \
  ros-hydro-moveit-core \
  ros-hydro-moveit-ros-move-group \
  ros-hydro-moveit-planners-ompl \
  ros-hydro-moveit-ros-visualization
```

2) Stop all ROS components and shutdown the roscore. Then run the youBot MoveIt! demo script (don't start any other nodes or launch files):

```
roslaunch youbot_moveit demo.launch
```

3) Setup a completely empty workspace with only the youbot-description and youbot-manipulation repositories (make sure that no other workspaces are sourced). Then try rebuilding and re-running the demo launch file. If it is not working, please send me the compelete output from the terminal.

Best regards
Sven

**Comment by StanleyYake** [comment] 2015-05-20 13:21
Dear svenschneider :
I'm glad about your reply, and finally I have found the reason under your guidence. When I source the `source /home/yake/catkin_ws/devel/setup.bash` and then `source /opt/ros/hydro/setup.bash` in my .bashrc file, it will truly pop up the red errors, but when I only  `source /home/yake/catkin_ws/devel/setup.bash` and all goes well, this is very weird , cause the official ROS tell us it will first look up catkin_ws and then /opt/ros/hydro/setup.bash.Thanks for kindness reply, BTW, I'm very interested in your ik code, found the solution is base on the robot Yasukawa Motoman L-3, which is trully different with youbot, although they are all 5DOF, and I want to talk about with you more detail, but I can't find your email or something to communicate with, looking forward to your reply, Sincerely Yake.
stone3949@gmail.com
![screenshot from 2015-05-20 21 20 23](https://cloud.githubusercontent.com/assets/7522853/7726653/0fdcb092-ff36-11e4-9255-9f0e83b53c08.png)

**Comment by StanleyYake** [comment] 2015-05-24 01:26
@svenschneider there is a gtest warning, and I din't care much about it ,actually I didn't run test your code ,cause I'm new to the gtest, where did I should  do first to use it ? your code is first one where I found the test code in it ,very good for your work, can you give me some advice on the test to start? Thanks for your great work. :+1: ![screenshot from 2015-05-24 09 17 01](https://cloud.githubusercontent.com/assets/7522853/7786304/126ddbc0-01f6-11e5-9cc1-1f6f773a05ec.png)

**Comment by svenschneider** [comment] 2015-05-26 11:11
Dear StanleyYake,

thank you for the information. However, I cannot reproduce this problem locally in a clean workspace. It would be really helpful, if you pasted the exact command(s) with all the text it output instead of the screenshot.

Last week (May 21) I have updated some of the tests (commits 6e72312146377feee8e64a3fd844b5fdb73d6b91 and 00ce2bcb490fcc795d09bcbd36c3d4f237886d2d). Did the warnings appear after you have pulled these changes? Unfortunately, the tests don't cover the core inverse kinematics code but instead only the MoveIt! plugin for the inverse kinematics.

Best regards
Sven

**Comment by svenschneider** [comment] 2015-07-27 13:55
Closing since everything seems to be working.

**Closed as completed by svenschneider** 2015-07-27 13:55 UTC

**Comment by 45960** [comment] 2016-11-23 11:43
Dear svenschneider,

i downloaded your code as a zipfile, included it in my catkin_ws and compiled it.
Everything was okay until i tried: roslaunch youbot_moveit demo.launch and i got:
`[ERROR] [1479900539.207770881]: The kinematics plugin (arm_1) failed to load. Error: According to the loaded plugin descriptions the class youbot_arm_kinematics_moveit::KinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  kdl_kinematics_plugin/KDLKinematicsPlugin pr2_arm_kinematics/PR2ArmKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
[ERROR] [1479900539.207944421]: Kinematics solver could not be instantiated for joint group arm_1.
`
Afterwards i tried to solve the problem with my source-files as described in the previous comment, but it won't fix the problem.
Furthermore i would like to use the solver for an arm_only youbot environment, but i can't include it in my setup_assistant.

Do u have any suggestions?

Best regards
ali

**Comment by svenschneider** [comment] 2016-11-28 15:18
Dear ali,

it seems that the youbot-manipulation repository has either not been build or at least is not available during runtime. Thus, could you please add the following information:
- Ubuntu and ROS version
- The complete build log
- The complete launch log

Also please try out the following steps:
- Can ROS find the youbot-manipulation package? For instance, execute the following command in your shell and validate that you are in the youbot-manipulation package afterwards
```
roscd youbot_manipulation
```
- Follow the installation instructions as described in the README.md file, especially the wstool commands. Note that I just fixed the version to be downloaded by wstool (before it was still pointing to hydro, now it is pointing to indigo).

Best regards
Sven

**Comment by 45960** [comment] 2016-11-29 15:52
Hey Sven,

Thank you for your answer!
i just installed the package for a second and third time and afterwards the problems were gone. I don't know why but it seems like the package is working pretty well.

I included the solver you made in my arm-only moveit application and it works pretty well. I would like to couple my moveit model with the real youbot-arm. Can you tell me which files i have to adapt to couple the both robots and generate a "digital twin" ?

Thank you!
ali
